### ISSUE TITLE
PR2 demos?

### ISSUE THREAD

**Issue by v4hn** [MarcToussaint/robotic#8]
Hi Marc,

I looked at your rai stack(s) a few years back and was really impressed back then by a LGP demonstration where a PR2 was tasked to move a number of objects from one table to a different table area, carrying at most one object in each gripper.
I remember a number of visualization windows popped up for the different considered task skeletons.
I looked for the same code again today, but could not find it anymore.
Am I looking in the wrong place?

**Comment by MarcToussaint** [comment]
Hi Michael,

the test still runs. Ideally, the following "should work" (e.g. on a standard Ubuntu 22.04):

git clone https://github.com/MarcToussaint/rai.git
cd rai
git checkout marc
make -j1 installUbuntuAll
cd test/LGP/pickAndPlace
make
./x.exe

... but that's only a 'should work', as I decided to not robustly distribute rai itself, but only derivatives (like the robotic python package). Perhaps you need to checkout the 'marc' branch rather than 'master'

The test still uses the old LGPTree code, but became slower as the default hyperparameters changed over the years and are not optimized for this application anymore. Also, depending on concrete applications we started using other solver architectures (still based on KOMO and skeletons, but not on that specific LGPTree implementation), that are more robust and integrate sample-based methods....

Best,
Marc

**Comment by v4hn** [comment]
Thank you for the direct reply! I just submitted a PR for rai to fix a number of issues I encountered looking into it.

> became slower as the default hyperparameters changed over the years

Whether slow is an issue really depends on your expectations :angel: TAMP is allowed take time after all.

> depending on concrete applications we started using other solver architectures (still based on KOMO and skeletons, but not on that specific LGPTree implementation), that are more robust and integrate sample-based methods.

References and/or implementations for that would be greatly appreciated!

**Comment by v4hn** [comment]
Meanwhile I will close the issue as you addressed the question.
